//APARTIR DE LA DIRECCION $0100, ESCRIBIR LOS 20 PRIMEROS NUMEROS(0-19)


.INCLUDE  "m328pdef.inc"

//XH, XL ES EL PUNTERO A LA TABLA
//R16 ES TEL CONTADOR EN BUCLE
//R17 ES EL DATO A ESCRIBIR EN LA TABLA


main:  LDI R16, 0 ; R16<-- 0
	   LDI R17, 0 ; R17<-- 0

//INICIALIZAO PUNTERO
       LDI XH, $01
	   LDI XL, $00

BUCLE:  ST X+, R17 ; GUARDA EL DATO EN R17 EN X, Y LUEGO INCREMENTA
        INC R17
		INC R16 
		CPI R16,20
		BRLO bucle



FIN: RJMP FIN
